---
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
    toc: false
editor_options: 
  chunk_output_type: console
---

We will be working off [these R tutorials](https://ohsuitg-my.sharepoint.com/:f:/g/personal/wakim_ohsu_edu/EhTBEvNn3MZHvD0NfnARUR4BleqEPYWy2nxRKI17tij2dw?e=vYnQtD){target="_blank"} from my Epi 525 class

# Schedule

| Week | Date | Lesson | Topic | Video | Slides HTML | Slides PDF | Slides Notes | Activity |
|----|----|----|----|:--:|:--:|:--:|:--:|:---|
| 1 | 7/9 | R01 | Download R and RStudio | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_500_25Su/Student_files/Recordings/R01_R02_R_Basics.mp4?csf=1&web=1&e=l2F7Jc)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/R01_Download_R/R01_Download_R.qmd)]{target="_blank" style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/R01_Download_R/R01_Download_R.pdf)]{style="color:#f8f5f0;"} |  | In class: download R and Rstudio |
|  |  | R02 | R Basics, part 1 | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R02_Basics_01/R02_Basics_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R02_Basics_01/R02_Basics_01.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R02_Basics_01/R02_Basics_01_work.R)]{style="color:#f8f5f0;"} |  |
| 2 | 7/16 | R03 | R Basics, part 2 | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_500_25Su/Student_files/Recordings/R03_R_Basics_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=OcomXm)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_500_25Su/Student_files/Recordings/R03_R_Basics_02_2024-10-09.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=gxJ8Mn)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R03_Basics_02/R03_Basics_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R03_Basics_02/R03_Basics_02.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R03_Basics_02/R03_Basics_02_work.R)]{style="color:#f8f5f0;"} | In class: Work through Iris dataset example + troubleshooting |
|  | In class on 7/16 | R04 | Reproducibility, File Organization, and Projects | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_500_25Su/Student_files/Recordings/R04_Reproducibility.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=AztwYw)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R04_Reproducibility/R04_Reproducibility.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R04_Reproducibility/R04_Reproducibility.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | In class: Make project folder for this class |
| 3 | 7/23 | R05 | Intro to Quarto, packages, and importing data | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_500_25Su/Student_files/Recordings/R05_Quarto.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=UC73B2)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_500_25Su/Student_files/Recordings/R05_Quarto_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=O5vulJ)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R05_Quarto_01/R05_Quarto_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R05_Quarto_01/R05_Quarto_01.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | In class: Make `.qmd` and complete R exercise in [this Homework](https://nwakim.github.io/EPI_525_25F/homework/HW_04.html#r-exercise-1) |
| 4 | 7/30 | R06 | `ggplot` , part 1 | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_500_25Su/Student_files/Recordings/R06_ggplot_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=VtK7wx)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R06_ggplot_01/R06_ggplot_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R06_ggplot_01/R06_ggplot_01.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | In class: Make `.qmd` and complete R exercise in [this Homework](https://nwakim.github.io/EPI_525_25F/homework/HW_05.html#r1-nhanes) |
| 5 | 8/6 | R07 | LaTeX in Quarto | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_500_25Su/Student_files/Recordings/R07_LaTeX.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=2t8dx0)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R07_LaTeX/R07_LaTeX.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R07_LaTeX/R07_LaTeX.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  |
| 6 | 8/13 | R08 | Transforming and subetting data with `tidyverse` | [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_500_25Su/Student_files/Recordings/R08_tidyverse_01.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=erXqbg)]{style="color:#f8f5f0;"} [[{{< iconify mdi video size=34px >}}](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/BSTA_500_25Su/Student_files/Recordings/R08_tidyverse_02.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=QY3Yc8)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01_notes.pdf) [{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01_notes.qmd)]{style="color:#f8f5f0;"} | In class: work with `chol` data, wide to long, subetting, etc. |
| 7 | 8/20 | R09 | Summarizing data with `tidyverse` and Table 1 | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R09_tidyverse_02/R09_tidyverse_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R09_tidyverse_02/R09_tidyverse_02.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R09_tidyverse_02/R09_tidyverse_02_notes.pdf)]{style="color:#f8f5f0;"} | In class: go over slides with pauses for activity, not sure why there is no video (??) |
| 8 | 8/27 |  | Flex week |  |  |  |  |  |
| 9 | 9/3 |  | Flex week |  |  |  |  |  |

: {.striped .hover tbl-colwidths="\[4, 4, 4, 20, 4,4, 4, 4, 20\]"}

------------------------------------------------------------------------

::::: grid
::: g-col-9
:::

::: g-col-3
[{{< iconify icomoon-free github size=24px >}} View the source on GitHub](https://github.com/nwakim/BSTA_500_25Su)
:::
:::::
